passed all edited gofiles to vet and lint; fixed syntax errors

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -12,35 +12,36 @@
 #
 # This script does not handle file names that contain spaces.
 
-govet=$(go vet ./lib)
-if [[ ! -z "$govet" ]]; then
-	echo "go vet checks not passed: Exit code $govet \n"
+gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')
+[ -z "$gofiles" ] && exit 0
+
+govet=$(go vet $gofiles)
+retcode=$?
+if [ ! -z "$govet" ]; then
+	echo "go vet checks not passed: Exit code $retcode \n"
 	exit 1
 fi
 
-lint=$(golint -set_exit_status)
-if [[ ! -z "$golint" ]]; then
-	echo "golint checks not passed: Exit code $golint\n"
+golint=$(golint -set_exit_status $gofiles)
+retcode=$?
+if [ ! -z "$golint" ]; then
+	echo "golint checks not passed: Exit code $retcode\n"
 	exit 1
 fi
 
 build=$(go build)
-if [[ $? -ne 0 ]]; then
-	echo "commit failed to build: return code $build\n"
+retcode=$?
+if [ $? -ne 0 ]; then
+	echo "commit failed to build: return code $retcode\n"
 	exit $build
 fi
-
-gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')
-
-gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')
-[ -z "$gofiles" ] && exit 0
 
 unformatted=$(gofmt -l $gofiles)
 [ -z "$unformatted" ] && exit 0
 
 # run gofmt on improperly formatted files.
 for fn in $unformatted; do
-	gofmt -w -e $PWD/$fn
+	gofmt -w $PWD/$fn
 	git add $PWD/$fn
 done
 
